--TABELA ZA BIRACKO MESTO
CREATE TABLE BIRACKO_MESTO(
ID INT PRIMARY KEY,
OPSTINA VARCHAR(125),
R_BROJ INT,
ADRESA VARCHAR(125),
UKUPNO_GLASACA INT,
UKUPNO_LISTICA INT,
VAZECI_LISTICI INT
);

--TABELA ZA UCESNIKE IZBORA
CREATE TABLE UCESNIK(
ID INT PRIMARY KEY,
NAZIV VARCHAR(125),
NOSILAC_LISTE VARCHAR(125),
REDNI_BROJ INT
)

--TABELA ZA REZULTATE IZBORA
CREATE TABLE REZULTATI(
ID_BIRACKO_MESTO INT,
ID_UCESNIK INT,
BROJ_GLASOVA INT,
PRIMARY KEY(ID_BIRACKO_MESTO, ID_UCESNIK),
FOREIGN KEY (ID_BIRACKO_MESTO) REFERENCES BIRACKO_MESTO(ID),
FOREIGN KEY(ID_UCESNIK) REFERENCES UCESNIK(ID)
)

-------------------------------------------------------------------------------------------------
--UPITI
-------------------------------------------------------------------------------------------------

--A) IME I PREZIME SVIH UCESNIKA IZBORA SA VISE OD 1000 GLASOVA

SELECT DISTINCT U.NAZIV
FROM UCESNIK U
JOIN REZULTATI R ON U.ID=R.ID_UCESNIK
WHERE R.BROJ_GLASOVA > 1000
ORDER BY U.NAZIV DESC

--B) IME I PREZIME UCESNIKA SA NAJVECIM BROJEM GLASOVA

SELECT  U.NAZIV
FROM UCESNIK U
JOIN REZULTATI R ON U.ID = R.ID_UCESNIK
GROUP BY U.NAZIV
ORDER BY SUM(R.BROJ_GLASOVA) DESC

--C) VISE OD 5% NEVAZECIS LISTICA I VISE OD 2000 GLASOVA

SELECT BM.ID, U.NAZIV, R.BROJ_GLASOVA
FROM BIRACKO_MESTO BM
JOIN REZULTATI R ON BM.ID = R.ID_BIRACKO_MESTO
JOIN UCESNIK U ON R.ID_UCESNIK= U.ID
WHERE BM.UKUPNO_LISTICA * 0.05 < BM.VAZECI_LISTICI
AND R.BROJ_GLASOVA > 2000;