--TABELA ZA IZVODJACE
CREATE TABLE IZVODJAC (
IDIZV INT PRIMARY KEY,
NAZIVIMEPR VARCHAR(125),
KONTAKTTEL VARCHAR(20)
);

--TABELA ZA DISKOGRAFKE KUCE
CREATE TABLE IZDKUCA(
IDIK INT PRIMARY KEY,
IME VARCHAR(25),
TELEFON VARCHAR(20)
);

--TABELA ZA KONCERTE
CREATE TABLE KONCERT(
IDKONC INT PRIMARY KEY,
NAZIVKONC VARCHAR(25),
MESTO VARCHAR(25),
GODINA INT NOT NULL,
BRKARATA INT NOT NULL,
CENA_KARTE INT
);

--TABELA ZA MENADZERE
CREATE TABLE MENADZER(
IDMEN INT PRIMARY KEY,
PREZIME VARCHAR(25),
IME VARCHAR(25),
PROCENAT INT,
BONUS INT
);

--TABELA ZA ALBUME
CREATE TABLE ALBUM(
IDALBUMA INT PRIMARY KEY,
NAZIV VARCHAR(25),
FORMAT VARCHAR(10),
GODINA INT,
VRSTA VARCHAR(25),
TIRAZ INT,
IDIK INT,
IDIZV INT,
FOREIGN KEY (IDIK) REFERENCES IZDKUCA(IDIK),
FOREIGN KEY (IDIZV) REFERENCES IZVODJAC(IDIZV)
);

--TABELA ZA PESME
CREATE TABLE PESMA(
IDPESME INT PRIMARY KEY,
RBROJ INT,
NAZIV VARCHAR(25),
IDALBUMA INT,
FOREIGN KEY (IDALBUMA) REFERENCES ALBUM(IDALBUMA)
);


--TABELA SA INFORMACIJAMA O SVIRKAMA
CREATE TABLE SVIRA(
IDIZV INT,
IDKONC INT,
CENA INT,
IDMEN INT,
PRIMARY KEY (IDIZV, IDKONC),
FOREIGN KEY (IDIZV) REFERENCES IZVODJAC(IDIZV),
FOREIGN KEY (IDKONC) REFERENCES KONCERT(IDKONC),
FOREIGN KEY (IDMEN) REFERENCES MENADZER(IDMEN)
);

--INFORMACIJE O IZVEDENIM PESMAMA
CREATE TABLE IZVEDENA(
IDPESME INT,
IDIZV INT,
IDKONC INT,
SNIMLJENJA VARCHAR(2),
PRIMARY KEY(IDPESME, IDIZV, IDKONC),
FOREIGN KEY (IDPESME) REFERENCES PESMA(IDPESME),
FOREIGN KEY (IDIZV) REFERENCES IZVODJAC(IDIZV),
FOREIGN KEY (IDKONC) REFERENCES KONCERT(IDKONC),
);

------------------------------------------------------------
--UPITI--
------------------------------------------------------------
--A) BROJ LJUDI KOJI SU VIDELI IZVODJENJE PESME AUBERGE OD CHRIS REA NA SVIM KONCERTIMA

SELECT SUM(K.BRKARATA) AS BROJ_LJUDI
FROM IZVEDENA I
JOIN KONCERT K ON I.IDKONC=K.IDKONC
JOIN PESMA P ON I.IDPESME=P.IDPESME
JOIN IZVODJAC IZ ON I.IDIZV=IZ.IDIZV
WHERE P.NAZIV='AUBERGE' AND IZ.NAZIVIMEPR='CHRIS REA';

--B)PESME SA ALBUMA APOKALIPSO OD DARKA RUNDEKA KOJE NISU IZVEDENE NA KONCERTU

SELECT DISTINCT P.NAZIV
FROM PESMA P
JOIN ALBUM A ON P.IDALBUMA=A.IDALBUMA
LEFT JOIN IZVEDENA I ON P.IDPESME=I.IDPESME
LEFT JOIN KONCERT K ON I.IDKONC=K.IDKONC
WHERE A.NAZIV = 'APOKALIPSO' AND 
(K.NAZIVKONC IS NULL OR K.NAZIVKONC !='30 GODINA DOMA OMLADINE');

--C)IZVODJACI KOJI SU PREMASILI PROSECNI TIRAZ 

SELECT IZ.NAZIVIMEPR AS IME_IZVODJACA, 
A.NAZIV AS NAZIV_ALBUMA, 
A.TIRAZ FROM ALBUM A
JOIN IZVODJAC IZ ON A.IDIZV = IZ.IDIZV
WHERE A.TIRAZ > (SELECT AVG(TIRAZ) FROM ALBUM WHERE IDIZV=IZ.IDIZV);

