CREATE TABLE [PREDUZECE].[dbo].[RADNIK](
lime varchar(15) not null,
sslovo char(1),
prezime varchar(20),
jmbg integer not null,
datrodj date,
pol char(1),
plata real,
jmbgruk integer,
idsek integer,
);

CREATE TABLE [PREDUZECE].[dbo].[SEKTOR](
naziv varchar(20),
idsek integer not null,
jmbgruk integer, 
datpost date,
);

CREATE TABLE [PREDUZECE].[dbo].[PROJEKAT](
naziv varchar(20),
idproj integer not null,
lokproj varchar(20),
idsek integer not null,
);

CREATE TABLE [PREDUZECE].[dbo].[RADI_NA](
jmbgrad integer not null,
idproj integer not null,
sati real,
);

CREATE TABLE [PREDUZECE].[dbo].[LOK_SEK](
idsek integer not null,
lokacija varchar(20),
);

CREATE TABLE [PREDUZECE].[dbo].[CLAN_PORODICE](
jmbgrad integer not null,
ime varchar(20) not null,
pol char(1) not null,
srodstvo varchar(20) not null,
datrodj date,
);






INSERT INTO [PREDUZECE].[dbo].[SEKTOR]
(NAZIV, IDSEK, JMBGRUK, DATPOST)
VALUES ('RAZVOJ', 5, 333445555, '22-JUN-1978');

INSERT INTO [PREDUZECE].[dbo].[SEKTOR]
(NAZIV, IDSEK, JMBGRUK, DATPOST)
VALUES ('ADMINISTRACIJA', 4, 987654321, '01-JAN-1985');

INSERT INTO [PREDUZECE].[dbo].[SEKTOR]
(NAZIV, IDSEK, JMBGRUK, DATPOST)
VALUES ('RUKOVODSTVO', 1, 888665555, '19-JUN-1971');



INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA, JMBGRUK, IDSEK)
VALUES( 'DJORDJE', 'B', 'SAVIC', 123456789, '09-JAN-1955', 'M', 3000, 333445555, 5);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA,  JMBGRUK, IDSEK)
VALUES( 'VOJA', 'V', 'VASIC', 333445555, '09-DEC-1945', 'M', 7000, NULL, 5);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA,  JMBGRUK, IDSEK)
VALUES( 'ANA', 'J', 'PETROVIC', 999887777, '19-JUL-1958', 'Z', 3500, 987654321, 4);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA, JMBGRUK, IDSEK)
VALUES( 'JELENA', 'S', 'MARKOVIC', 987654321, '20-JUN-1965', 'Z', 5300, 888665555, 4);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA, JMBGRUK, IDSEK)
VALUES( 'RATKO', 'K', 'VELJKOVIC', 666884444, '15-SEP-1952', 'M', 3800, 333445555, 5);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA, JMBGRUK, IDSEK)
VALUES( 'MILICA', 'A', 'STOJIC', 456456456, '31-JUL-1962', 'Z', 2500, 333445555, 5);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA,  JMBGRUK, IDSEK)
VALUES( 'JOVAN', 'V', 'JANKOVIC', 987987987, '29-MAR-1959', 'M', 2500, 987654321, 4);

INSERT INTO [PREDUZECE].[dbo].[RADNIK]
(LIME, SSLOVO, PREZIME, JMBG, DATRODJ, POL, PLATA,  JMBGRUK, IDSEK)
VALUES( 'IVAN', 'E', 'PERIC', 888665555, '09-JAN-1955', 'M', 5500, NULL, 5);



INSERT INTO [PREDUZECE].[dbo].[PROJEKAT]
(NAZIV, IDPROJ, LOKPROJ, IDSEK)
VALUES( 'PROIZVODX', 1, 'NIS', 5);

INSERT INTO [PREDUZECE].[dbo].[PROJEKAT]
(NAZIV, IDPROJ, LOKPROJ, IDSEK)
VALUES( 'PROIZVODY', 2, 'BEOGRAD', 5);

INSERT INTO [PREDUZECE].[dbo].[PROJEKAT]
(NAZIV, IDPROJ, LOKPROJ, IDSEK)
VALUES( 'PROIZVODZ', 3, 'JAGODINA', 5);

INSERT INTO [PREDUZECE].[dbo].[PROJEKAT]
(NAZIV, IDPROJ, LOKPROJ, IDSEK)
VALUES( 'KOMPJUTERIZACIJA', 10, 'LESKOVAC', 4);

INSERT INTO [PREDUZECE].[dbo].[PROJEKAT]
(NAZIV, IDPROJ, LOKPROJ, IDSEK)
VALUES( 'REORGANIZACIJA', 20, 'BEOGRAD', 1);

INSERT INTO [PREDUZECE].[dbo].[PROJEKAT]
(NAZIV, IDPROJ, LOKPROJ, IDSEK)
VALUES( 'NOVI_DOBICI', 30, 'LESKOVAC', 4);



INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL, SRODSTVO, DATRODJ)
VALUES( 333445555, 'ALISA', 'Z','cerka', '05-APR-1976');

INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL,SRODSTVO, DATRODJ)
VALUES( 333445555, 'TODOR', 'M','otac', '25-OCT-1973');

INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL,SRODSTVO, DATRODJ)
VALUES( 333445555, 'MILA', 'Z','cerka', '03-JUN-1978');

INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL,SRODSTVO, DATRODJ)
VALUES( 987654321, 'MARKO', 'M','otac', '29-FEB-1980');

INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL,SRODSTVO, DATRODJ)
VALUES( 123456789, 'MIHAJLO', 'M','sin', '02-JAN-1978');

INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL,SRODSTVO, DATRODJ)
VALUES( 123456789, 'ALISA', 'Z','cerka', '31-DEC-1988');

INSERT INTO [PREDUZECE].[dbo].[CLAN_PORODICE]
(JMBGRAD, IME, POL,SRODSTVO, DATRODJ)
VALUES( 123456789, 'LIDIJA', 'Z','cerka', '05-JUL-1983');


INSERT INTO LOK_SEK
(IDSEK, LOKACIJA)
VALUES( 1, 'BEOGRAD');


INSERT INTO LOK_SEK
(IDSEK, LOKACIJA)
VALUES( 4, 'LESKOVAC');

INSERT INTO LOK_SEK
(IDSEK, LOKACIJA)
VALUES( 5, 'NIS');

INSERT INTO LOK_SEK
(IDSEK, LOKACIJA)
VALUES( 5, 'BEOGRAD');

INSERT INTO LOK_SEK
(IDSEK, LOKACIJA)
VALUES( 5, 'JAGODINA');




INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 123456789, 1, 32.5);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 123456789, 2, 7.5);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 333445555, 2, 10.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 333445555, 3, 10.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 333445555, 10, 10.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 333445555, 20, 10.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 666884444, 3, 40.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 456456456, 1, 20.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 456456456, 2, 20.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 999887777, 30, 30.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 999887777, 10, 10.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 987987987, 10, 35.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 987987987, 30, 5.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 987654321, 30, 20.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 987654321, 20, 15.0);

INSERT INTO [PREDUZECE].[dbo].[RADI_NA]
(JMBGRAD, IDPROJ, SATI)
VALUES( 888665555, 20, null);



ALTER TABLE [PREDUZECE].[dbo].[RADNIK]
ADD CONSTRAINT RADNIK_PK PRIMARY KEY (JMBG) ;



ALTER TABLE [PREDUZECE].[dbo].[SEKTOR]
ADD CONSTRAINT SEKTOR_PK PRIMARY KEY (IDSEK) ;



ALTER TABLE [PREDUZECE].[dbo].[PROJEKAT]
ADD CONSTRAINT PROJEKAT_PK PRIMARY KEY (IDPROJ) ;



ALTER TABLE [PREDUZECE].[dbo].[RADI_NA]
ADD CONSTRAINT RADI_NA_PK PRIMARY KEY (JMBGRAD,IDPROJ) ;



ALTER TABLE [PREDUZECE].[dbo].[CLAN_PORODICE]
ADD CONSTRAINT CLAN_PORODICE_PK PRIMARY KEY (JMBGRAD,IME) ;







ALTER TABLE [PREDUZECE].[dbo].[RADNIK]
ADD CONSTRAINT SEKTOR_FK FOREIGN KEY (IDSEK) REFERENCES SEKTOR(IDSEK);



ALTER TABLE [PREDUZECE].[dbo].[RADI_NA]
ADD CONSTRAINT RADI_NA_FK1 FOREIGN KEY (JMBGRAD) REFERENCES RADNIK(JMBG);



ALTER TABLE [PREDUZECE].[dbo].[RADI_NA]
ADD CONSTRAINT RADI_NA_FK2 FOREIGN KEY (IDPROJ) REFERENCES PROJEKAT(IDPROJ);



ALTER TABLE [PREDUZECE].[dbo].[CLAN_PORODICE]
ADD CONSTRAINT CLAN_PORODICE_FK FOREIGN KEY (JMBGRAD) REFERENCES RADNIK(JMBG);

