
--Radnici koji se prezivaju savic a rade na nekom projektu
--radnici se nalaze u tabli radnik
--kako znamo na kom projektu radi neki radnik? koja je to tabela?
--odgovor: to je tabela radi_na
(SELECT DISTINCT R.LIME, R.PREZIME, R.PLATA
FROM RADNIK R INNER JOIN RADI_NA RN ON R.JMBG = RN.JMBGRAD
WHERE PREZIME = 'SAVIC')
UNION

--RADNICI KOJI SE PREZIVAJU SAVIC A RUKOVODE SEKTORIMA KOJI IZVODE PROJEKTE
(SELECT R.LIME, R.PREZIME, R.PLATA
FROM RADNIK R INNER JOIN SEKTOR S ON S.JMBGRUK = R.JMBG
WHERE R.PREZIME = 'VASIC')

--ODREDITI IMENA I PREZIMENA RADNIKA KOJI RADE NA PROJEKTIMA LOCIRANIM U BG
(SELECT DISTINCT R.LIME, R.PREZIME 
FROM RADNIK R INNER JOIN RADI_NA RN ON R.JMBG= RN.JMBGRAD 
INNER JOIN PROJEKAT P ON RN.IDPROJ = P.IDPROJ
WHERE P.LOKPROJ LIKE '%BEOGRAD')
INTERSECT
--I CIJA SU PRIMANJA VECA OD 5000 DINARA
(SELECT R.LIME, R.PREZIME
FROM RADNIK R
WHERE R.PLATA > 5000
)

--IMENA I PREZIMENA SVIH RUKOVODIOCA SEKTORA
SELECT DISTINCT R.LIME, R.PREZIME
FROM RADNIK R INNER JOIN SEKTOR S ON S.JMBGRUK = R.JMBG 
INNER JOIN CLAN_PORODICE CP ON R.JMBG = CP.jmbgrad;

SELECT R.LIME, R.PREZIME
FROM RADNIK R
WHERE NOT EXISTS(SELECT * FROM CLAN_PORODICE CP WHERE CP.JMBGRAD = R.JMBG)


SELECT SUM(PLATA) AS 'ZBIR PLATA', MIN(PLATA) 
AS 'NAJNIZA PLATA', MAX(PLATA) AS 'NAJVECA PLATA', 
AVG(PLATA) AS 'PROSECNA PLATA'
FROM RADNIK


--NACI RADNIKA KOJI IMA MAX PLATU
SELECT TOP 1 R.LIME, R.PREZIME, R.PLATA FROM RADNIK R
ORDER BY PLATA DESC

--NACI RADNIKE KOJE IMAJU PLATU ISPOD PROSECNE
SELECT R.LIME, R.PREZIME, R.PLATA FROM RADNIK R
WHERE R.plata < (SELECT AVG(PLATA) FROM RADNIK)

--KOLIKO RADNIKA RADI U SEKTORU RAZVOJ
SELECT COUNT(*) AS 'BROJ RADNIKA'
FROM RADNIK R INNER JOIN SEKTOR S ON R.idsek = S.idsek
WHERE S.naziv = 'RAZVOJ'

--NACI RADNIKA KOJI IMA MAX PLATU
SELECT TOP 1 R.LIME, R.PREZIME, R.PLATA
FROM RADNIK R
ORDER BY PLATA DESC

--NACI RADNIKE KOJI IMAJU PLATU ISPOD PROSECNE
SELECT R.LIME, R.PREZIME, R.PLATA FROM RADNIK R
WHERE R.PLATA < (SELECT AVG(plata) FROM RADNIK)

--IMENA I PREZIMENA RADNIKA KOJI IMAJU VISE OD DVA CLANA PORODICE
SELECT R.LIME, R.PREZIME FROM RADNIK R
WHERE (SELECT COUNT(*) FROM CLAN_PORODICE WHERE jmbgrad = R.jmbg) > 2

--ZA SVE SEKTORE NAVESTI BROJ SEKTORA , BROJ RADNIKA I PROSECNU PLATU

--ZA SVE PROJEKTE NA KOJIMA RADI VISE OD DVA RADNIKA PRIKAZATI 
--BR PROJEKTA, IME PROJEKTA I BR RADNIKA KOJI NA NJEMU RADE

SELECT P.IDPROJ, P.NAZIV, COUNT(*) AS 'BROJ RADNIKA'
FROM RADI_NA RN INNER JOIN PROJEKAT P
ON RN.idproj = P.idproj
GROUP BY P.IDPROJ, P.NAZIV
HAVING COUNT(*) > 2

--ISPISATI KOLIKO IMA SEKTORA KOJI SE NALAZE U BEOGRADU

SELECT COUNT(*) AS 'BROJ SEKTORA'
FROM LOK_SEK
WHERE LOKACIJA LIKE '%BEOGRAD'

--ISPISATI KOLIKO IMA SEKTORA PO LOKACIJAMA

SELECT LOKACIJA, COUNT(*) AS 'BROJ SEKTORA PO LOKACIJAMA'
FROM LOK_SEK
GROUP BY LOKACIJA

--INDEX IME PREZIME STUDENTA SA NAJBOLJIM PROSEKOM
--NEMOGUCE URADITI ZADATAK ZBOG NEDOSTATKA PODATAKA U BAZI

SELECT P.NAZIV FROM PROJEKAT 