CREATE TABLE STUDENT(
BR_INDEX VARCHAR(11) PRIMARY KEY,
IME VARCHAR(15) NOT NULL,
PREZIME VARCHAR(20) NOT NULL,
ADRESA VARCHAR(30),
SEMESTAR INTEGER,
);

CREATE TABLE PROFESOR(
JMBG VARCHAR(13) PRIMARY KEY,
IME VARCHAR(15) NOT NULL,
PREZIME VARCHAR(20) NOT NULL,
);

CREATE TABLE PREDMET(
OZNAKA VARCHAR(5) PRIMARY KEY,
NAZIV VARCHAR(15) NOT NULL,
);

CREATE TABLE ROK(
OZNAKA_ROKA VARCHAR(3),
GODINA_ROKA INTEGER,
PRIMARY KEY(OZNAKA_ROKA, GODINA_ROKA)
);

CREATE TABLE SLUSA(
INDEX_STUDENTA VARCHAR(11) REFERENCES STUDENT(BR_INDEX),
OZNAKA_PREDMETA VARCHAR(5) REFERENCES PREDMET(OZNAKA),
PRIMARY KEY(INDEX_STUDENTA, OZNAKA_PREDMETA)
);

CREATE TABLE PREDAJE(
JMBG_PROFESORA VARCHAR(13) REFERENCES PROFESOR(JMBG),
OZNAKA_PREDMETA VARCHAR(5) REFERENCES PREDMET(OZNAKA),
PRIMARY KEY(JMBG_PROFESORA, OZNAKA_PREDMETA)
);

CREATE TABLE ISPIT(
PROFESOR VARCHAR(13), 
STUDENT VARCHAR(11),
PREDMET VARCHAR(5),
ROK VARCHAR(3) NOT NULL,
GODINA INTEGER NOT NULL,
DATUM DATE,
OCENA INTEGER NOT NULL,
FOREIGN KEY(PROFESOR, PREDMET) 
REFERENCES PREDAJE(JMBG_PROFESORA, OZNAKA_PREDMETA ),
FOREIGN KEY(STUDENT, PREDMET) 
REFERENCES SLUSA(INDEX_STUDENTA, OZNAKA_PREDMETA),
FOREIGN KEY(ROK, GODINA)
REFERENCES ROK(OZNAKA_ROKA, GODINA_ROKA),
PRIMARY KEY(STUDENT, PREDMET, PROFESOR, DATUM)
);