--RADNICI SA PLATOM MANJOM OD (PROIZVOLJNOG BROJA)
SELECT * FROM RADNIK
WHERE PLATA < 5000;

--RUKOVODILAC JOVAN
SELECT * FROM SEKTOR
WHERE jmbgruk = (SELECT jmbgruk
FROM RADNIK WHERE LIME = 'JOVAN')

--SVE LOKACIJE SEKTORA RAZVOJ
SELECT LOKACIJA 
FROM LOK_SEK
WHERE idsek = (SELECT idsek 
FROM SEKTOR WHERE naziv = 'RAZVOJ');

--CLANOVI PORODICE U SRODSTVU "SUPRUGA" SA NEKIM RADNICI
SELECT * FROM CLAN_PORODICE
WHERE srodstvo = 'CERKA';

--SVE RADNIKE CIJI JE SEF PETAR
SELECT *
FROM RADNIK
WHERE jmbg = (SELECT jmbgruk FROM RADNIK WHERE lime = 'PETAR');

--maticne brojeve svih sefora
SELECT DISTINCT JMBGRUK AS MATICNI_BR_SEFA
FROM RADNIK
WHERE jmbgruk IS NOT NULL;

--DATUM RODJENJA RADNIKA CIJE JE IME MILICA A STOJIC
SELECT DATRODJ FROM RADNIK
WHERE lime = 'MILICA' AND sslovo = 'A' AND prezime = 'STOJIC';

--PRIKAZATI IMENA I PREZIMENA SVIH RADNIKA KOJI RADE U PREDUZECU ALI TAKO DA JE SPISAK SORTIRAN PREMA PREZIMENIMA RADSNIKA U RASTUCEM REDOSLEDU
SELECT LIME AS IME, PREZIME AS PREZIME
FROM RADNIK
ORDER BY PREZIME ASC;

--PRIKAZATI IMENA I PREZIMENA I PLATE RADNIKA KOJI ZARADJUJU
--IZMEDJU 80000 I 120000

SELECT LIME AS IME, PREZIME AS PREZIME, PLATA AS PLATA
FROM RADNIK
WHERE PLATA BETWEEN 3000 AND 5500;

--ODREDITI ZARADU SVIH RADNIKA ZAOKRUZENU NA DVE DECIMALE.
--U MESECU POSTOJI 22 RADNA DANA I 8H PO DANU
SELECT LIME AS IME, PREZIME AS PREZIME,
ROUND(((PLATA/22)/8),2) AS ZARADA_PO_SATU
FROM RADNIK;

--NACI SVE RADNIKE KOJI SU RODJENI PEDESETIH GODINA
SELECT * FROM RADNIK
WHERE datrodj LIKE '__5_%';

--NACI SVE RADNIKE KOJI ZIVE U NISU

-----
ALTER TABLE RADNIK
ADD ZANIMANJE VARCHAR(20);

UPDATE RADNIK
SET ZANIMANJE = 'ANALITICAR'
WHERE lime IN ('MILICA', 'DJORDJE', 'VOJA');

UPDATE RADNIK
SET ZANIMANJE = 'RUKOVODILAC'
WHERE LIME IN('ANA', 'VASA');

UPDATE RADNIK
SET ZANIMANJE = 'PREDSEDNIK'
WHERE LIME IN('RATKO', 'IVAN');

--KORISTECI ATRIBUT ZANIMANJE FORMIRATI ATRIBUT KLASA TAKO DA JE POSAO
--ANALITICARA KLASA1, ZA RUKOVODIOCA 3, PREDSEDNIKA 5 , A ZA OSTALE 2


--Radnici koji se prezivaju savic a rade na nekom projektu
--radnici se nalaze u tabli radnik
--kako znamo na kom projektu radi neki radnik? koja je to tabela?
--odgovor: to je tabela radi_na
(SELECT DISTINCT R.LIME, R.PREZIME, R.PLATA
FROM RADNIK R INNER JOIN RADI_NA RN ON R.JMBG = RN.JMBGRAD
WHERE PREZIME = 'SAVIC')
UNION

--RADNICI KOJI SE PREZIVAJU SAVIC A RUKOVODE SEKTORIMA KOJI IZVODE PROJEKTE
(SELECT R.LIME, R.PREZIME, R.PLATA
FROM RADNIK R INNER JOIN SEKTOR S ON S.JMBGRUK = R.JMBG
WHERE R.PREZIME = 'VASIC')

--ODREDITI IMENA I PREZIMENA RADNIKA KOJI RADE NA PROJEKTIMA LOCIRANIM U BG
(SELECT DISTINCT R.LIME, R.PREZIME 
FROM RADNIK R INNER JOIN RADI_NA RN ON R.JMBG= RN.JMBGRAD 
INNER JOIN PROJEKAT P ON RN.IDPROJ = P.IDPROJ
WHERE P.LOKPROJ LIKE '%BEOGRAD')
INTERSECT
--I CIJA SU PRIMANJA VECA OD 5000 DINARA
(SELECT R.LIME, R.PREZIME
FROM RADNIK R
WHERE R.PLATA > 5000
)

--IMENA I PREZIMENA SVIH RUKOVODIOCA SEKTORA
SELECT DISTINCT R.LIME, R.PREZIME
FROM RADNIK R INNER JOIN SEKTOR S ON S.JMBGRUK = R.JMBG 
INNER JOIN CLAN_PORODICE CP ON R.JMBG = CP.JMBGRUK;

SELECT R.LIME, R.PREZIME
FROM RADNIK R
WHERE NOT EXIST (SELECT * FROM CLAN_PORODICE CP WHERE CP.JMBGRAD = R.JMBG)


SELECT SUM(PLATA) AS 'ZBIR PLATA', MIN(PLATA) 
AS 'NAJNIZA PLATA', MAX(PLATA) AS 'NAJVECA PLATA', 
AVG(PLATA) AS 'PROSECNA PLATA'
FROM RADNIK

--NACI RADNIKA KOJI IMA MAX PLATU
--NACI RADNIKE KOJE IMAJU PLATU ISPOD PROSECNE

SELECT R.LIME, R.PREZIME, R.PLATA FROM RADNIK R
ORDER BY PLATA DESC